### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ZhiminPeng** [ZhiminPeng/arock-pkg-paper#13]
I will list the remaining todo list here:
# paper
- [x] Abstract. We need to write an abstract;
- [x] Conclusion. We also need a conclusion;
- [x] Literature review for existing packages;
- [x] Enhancing the writing of the other sections. 
- [x] Subsection for the how to write a kernel function.
- [x] Update the new numerical results.
# Coding
- [x] Coding. We need to clean up the codebase, and refactor the names;
- [ ] Documentation. The documentation needs more work.
